### ISSUE TITLE
Return code or no return code for key exchange?

### ISSUE THREAD

**Issue by LoupVaillant** [LoupVaillant/Monocypher#102]
In its early stage, Monocypher's key exchange primitives didn't have a return value. It has since [been introduced](https://github.com/LoupVaillant/Monocypher/commit/b7826a99ef11b6a65db251b872bf413dcb9c87f5#diff-b7175b069a24cabf8d434251283462fcL105), on the grounds that contributory behaviour matters, and Libsodium uses it (TweetNaCl doesn't).

I've always had a problem with this test. When both keys come from legitimate sources (as they do when two honest parties that know of each other's public keys beforehand), then there is no *need* for such a test. And I don't like to complicate the interface by adding a significant return value to a primitive that doesn't need one. This is also contrary to Monocypher's general philosophy of validating nothing (it's the user's responsibility to provide correct inputs). Besides, DJB himself says [we shouldn't validate](http://cr.yp.to/ecdh.html#validate). Still, this seemed small enough that I could just add it.

[This argument](https://moderncrypto.org/mail-archive/curves/2017/000896.html) by Trevor Perrin changed my mind:

- The check does have a cost: it's a conditional branch, and crypto must be cautious with them.
- When needed, the check is insufficient. If for instance the public key is a known multiple of the base point (such as 37, as suggested in the original paper), then anyone can reconstruct the shared secret. There is no reasonable way to test for this.
- To simplify the security analysis, we should only provide points that are on the curve. This means not on its twist. Validating *that* is way more expensive than just checking for all zero at the end.
- Most of all, such validation endorses protocols that rely on properties *outside the scope of Diffie Hellman key exchange*.

That last one is probably the most harmful. While curve25519 may have interesting properties besides ensuring DH works as intended, relying on those other properties makes a brittle protocol that may break if we change the underlying primitive. Also, those other security properties have probably received less scrutiny than the main one.

So I'm thinking about removing the check, incurring a minor breaking change in the API, thus bumping the version to 2.1.0. Any thought?

**Comment by dsprenkels** [comment]
Just looking at your library for the first time, so feel free to ignore this comment. My two cents:

Diffie-Hellman must *always* be authenticated, and thus the inputs *are always* valid. Even if they are not, the exception should not occur in the Diffie-Hellman exchange, but in the authentication check. Adding a check in the scalar multiplication would add a (timing) oracle.

**Comment by LoupVaillant** [comment]
Well, here's the thing: how do we authenticate Diffie-Hellman? Is it even possible? I'm new to protocol design, so I'm not sure how to go about it.

Imagine for instance you want to send an anonymous message to Laura Poitras or something. Here's how I'd do it of the top of my head:

- Generate an ephemeral key pair `e`, send the public key.
- Perform a key exchange `er` between `e` and the recipient's key `r`.
- Encrypt your payload with `Hash(er)`, send the ciphertext and authentication tag.

I'm not sure `e` can be authenticated here, even if it was added as additional data in the AEAD step. I mean, the message is anonymous. Yet this scheme is safe, if I recall correctly. The problem persists even if the message is not anonymous (using an ephemeral key for partial forward secrecy and identity hiding):

- Generate an ephemeral key pair `e`, send the public key.
- Perform a key exchange `er` between `e` and the recipient's key `r`.
- Encrypt your public key `s` with `Hash(er)`, send the ciphertext and authentication tag.
- Perform a second key exchange `sr`, between `s` and `r`.
- Encrypt the payload with `Hash(er | sr)`, send the ciphertext and authentication tag.

It looks like the recipient can validate `e` when the payload is received, though not before. That's quite a bit of cryptographic operations before the ephemeral key is validated. Still, this looks okay from where I stand.

My problem is, I don't fully understand *why* this looks okay. I might have forgotten something important there.

**Comment by dsprenkels** [comment]
Well if in this case `r` is statically defined (published in a newspaper or on a trusted website); you know that `r` actually belongs to the receiver. I.e. then it is authenticated. In this case the protocol would be secure.

The point is that the `r` share is actually trusted (/authenticated) here. so it is safe to run the DH algorithm on it (by which I mean we do not *lose* any security here). If it is unsafe, you authentication step will already have failed by this point.

(An important note is that obviously we do not transmit any payload before we trust that our channel is authenticated.)

**Comment by LoupVaillant** [comment]
As a sender, there is indeed no problem. As a *recipient* though… the ephemeral key I receive is not authenticated. Yet I still have to DH with it, and only *then* do I uncover the sender's public key (or other identifying information) that I know of.

How does the protocol makes sure this is still okay?

**Comment by dsprenkels** [comment]
The goal of the protocol is to establish a shared secret between Alice and Bob. The case when Alice would send a malicious share to attack the protocol, she would be attacking herself. If Alice wants to subvert the security of their channel she can just publish the established shared secret.

I.e. validating Alice's share would not add any security. Alice has other means to subvert the protocol.

> How does the protocol makes sure this is still okay?

Another way of seeing is that it indeed does not. But the attack would imply that Alice attacks herself, which we assume she won't (cause why would she?). As long as *one* of the endpoints authenticates the other we know that the channel is not being mitm'd.

**Comment by fscoto** [comment]
I've read through the discussion here and the linked mailing list post by Trevor Perrin. This is the part that really stands out to me is that there's are really only three types of (EC)DH key exchange:

**One pre-authenticated party** (e.g. client and server, where the client can generally rely on the server to be trusted and normally has a means of authenticating the connection to the server). In that case, the client is in charge of defending against a MITM by authenticating the server. The server *can and should* assume as much; the server thus does not care about weird DH inputs.

**Two pre-authenticated parties** (e.g. server to server, where both servers have means of authenticating the connection to each other). In that case, the DH after the authentication stage can be effectively blindly trusted. The argument that one of the servers could be compromised is pure theory: If the server is compromised, it doesn't need to send a bad DH pubkey; you just straight up dump the session keys.

**Two parties that cannot authenticate each other**. I'm struggling to find an example. Possibly one might think of P2P protocols, but a well-designed one would arguably a central means of authentication or allow anybody – including an attacker – to participate and thus lift any veil of secrecy.

My reply to this depends on *type 3 being an entirely unrealistic scenario*. If it is not entirely unrealistic, disregard all of the following and assume that the current state of affairs is very much preferable.

1. `crypto_key_exchange()` and `crypto_x25519()` should, in principle, return `void`.
2. I'd suggest not changing it. Yes, Monocypher is an opinionated library, but the decision has already been made. Monocypher is still young, but we've already shuffled the API around [once already](https://github.com/LoupVaillant/Monocypher/commit/f74ae86d53e541d38ca46afe050f2e17d1f774f1) after 1.0, namely for the `crypto_verify` family. But in that case, there was an extraordinary need. This is a cryptographic library, not a web browser; if we keep breaking the API a lot, it'll be hard to take Monocypher seriously. Even if the original API may be suboptimal, it's not fundamentally broken.
3. This change would break the API and ABI. Monocypher 3.0.0 would be in order. It "feels" like a change that would warrant at most 2.1.0, but semantic versioning [requires that the major be bumped because it is not backwards-compatible](https://semver.org/#spec-item-8). It should not impact anybody because type 3 is unrealistic and the "RETURN VALUES" section already notes that only untrustworthy keys need checking. But who really knows?
4. A note on the man pages for aforementioned functions should be added to "SECURITY CONSIDERATIONS" that makes clear:
    1. that applications should authenticate *before* performing the key exchange (this might even be a good idea to add even if we change nothing); and
    2. the complete list of checks for applications that do wish to make the check manually.

**Comment by LoupVaillant** [comment]
OK, we'll keep it as is. I will close the issue when the manual better reflects our current understanding, and states actionable advice.

One little problem: I'm not sure what the "complete list of checks" is. I _think_ that in the case of X25519 as implemented in Monocypher, we just need to check whether the result is a known constant. (If I recall correctly, that's because the twist of the curve has the same order as the curve itself, and thus is just as secure). Wouldn't work for many other curves, though.

**Comment by fscoto** [comment]
> I'm not sure what the "complete list of checks" is.

Neither am I. EC is definitely one of my weak points.

Having said that, I think we misunderstood each other. Only 4.i. was meant to be done if we change nothing. Everything else in that list was covered by "disregard all of the following and assume that the current state of affairs is very much preferable".

**Comment by LoupVaillant** [comment]
> These orders are _not_ the same.

Ah, so *this* is why Trevor Perrin said a proper check should ensure the point is on the curve, and not on its twist. Thanks.

> I would like to suggest considering the return value as being deprecated, and deferring the removal to when you will have to bump the major version sometime in the future (due to unrelated stuff).

That's what I had in mind as well. We could replace the "return values" section by something like:

> Return values are deprecated. Don't use them.
>
> `crypto_key_exchange()` returns -1 if the shared secret is a known constant. This happens with some illegitimate public keys. Some poorly designed protocols need to test for "contributory" behaviour, to make sure no untrusted party force the shared secret to the known constant.
>
> Properly designed protocols don't need this check. Instead, they authenticate the key they perform exchanges with by other means. _(I'm not sure about that last paragraph)_

Then the examples would be changed to something that doesn't check for return values. I may change the comments to remind the reader that "their public key" should be authenticated somehow. Or better yet mimic a key exchange as performed by the Noise protocol framework.

**Comment by LoupVaillant** [comment]
Manual updated, all done. Closing. Thank you all.
