### ISSUE TITLE
MSVC 2017 compiler warnings W4

### ISSUE THREAD

**Issue by mireiner** [LoupVaillant/Monocypher#112]
Hi there,

increasing MSVC 2017 compiler to warning level /W4 gives following warnings:

monocypher.c(153): warning C4244: 'Initialization': conversion from 'u32' to 'u8', possible loss of data
monocypher.c(1275): warning C4244: 'Initialization': conversion from 'int' in 'u8', possible loss of data
monocypher.c(1654): warning C4244: '=': conversion from 'int' to 'i8', possible loss of data
monocypher.c(1867): warning C4244: "Initialization": conversion from 'int' in 'u8', possible loss of data
monocypher.c(1725): warning C4456: Declaration of 'tmp' hides previous local declaration

The warnings issues may be cosmetic (for sure the last one). But you may like to know them anyway.

Best regards,
mireiner

**Comment by LoupVaillant** [comment]
Thanks, I'll fix them right away.

- Line 153: the loss of data is intentional, adding an explicit conversion.
- Line 1275: I was using the wrong type of integer. Harmless, but an error nonetheless.
- Line 1654: no loss of data in practice (only possible values are 0 and 1), adding an explicit conversion.
- Line 1867: no loss of data in practice (we never overflow), adding an explicit conversion.
- Line 1725: don't need a second temporary, might as well get rid of it and save some stack space.

**Comment by LoupVaillant** [comment]
There, done. Did it work?
