### ISSUE TITLE
crypto_key_exchange may leak shared_secret

### ISSUE THREAD

**Issue by amvtek** [LoupVaillant/Monocypher#15]
It looks to me that the shared_secret array shall be zeroed before returning from the function.

I am not familiar with HChaCha20 so what is done maybe OK in some context, but if the key is to be used as a session secret key you shall hash (Blake2B or SHA512) the  x25519 secret with the 2 public keys

**Comment by LoupVaillant** [comment]
> It looks to me that the shared_secret array shall be zeroed before returning from the function.

That's currently out of scope. Monocypher does not try to zero out anything, ever. This includes all contexes and temporary variables. It never leaks anything, as long as your program doesn't have an undefined behaviour that lets the attacker read your memory while you are working on crypto stuff. My current hypothesis is that if this happens, you are screwed anyway. Zeroing stuff out is not going to save you, the attacker can still read the session key itself, or worse, your long term secret key. TweetNaCl follows the same philosophy.

To avoid undefined behaviours, test and audit the hell out of your program with all the sanitisers you can grab, as well as Valgrind and the TIS-Interpreter if your can afford them. You can also bind Monocypher to a safe language (I believe someone is working on OCaml bindings).

To _mitigate_ undefined behaviour, isolate your sensitive code, preferably in a separate process like [qMail](http://hillside.net/plop/2004/papers/mhafiz1/PLoP2004_mhafiz1_0.pdf) does. If you insist on using C or C++ for your whole application, I think this one is mandatory.

> I am not familiar with HChaCha20 so what is done maybe OK in some context,

This is one such context. NaCl itself uses HSalsa20 for its `crypto_box()` API (this is easily checked in [TweetNaCl](http://tweetnacl.cr.yp.to/)'s sources). From what I have gathered, this is sufficient because the shared secret has enough entropy to begin with (128 bits of security to be more precise). HChacha20 is derived from Chacha20 the same way HSalsa20 is derived from Salsa20, and offers the same the same security guarantees: to break it, you have to break Chacha20 itself.

---

I'm closing this for now (we're halfway between "won't fix" and "not a bug"). Do re-open it if you have further objections, or arguments I may not be aware of. And, welcome, it's nice of you to contribute. :smiley:

**Comment by LoupVaillant** [comment]
I have since changed my mind. And by the way the issue is still not resolved. Reopening. We should use `crypto_wipe()` to erase `raw_shared_secret` before returning from `crypto_key_exchange()`.

Come to think of it, another pass wouldn't hurt: `raw_shared_secret` may not be the only secret temporary buffer Monocypher fails to erase.
