### ISSUE TITLE
Random number generation and the manual

### ISSUE THREAD

**Issue by CuleX** [LoupVaillant/Monocypher#2]
Throughout [the Monocypher Manual](http://loup-vaillant.fr/projects/monocypher/manual), recommendations saying to use the operating system's RNG can be found. That is in and of itself probably good advice, but if your goal is being ["easy to deploy"](http://loup-vaillant.fr/projects/monocypher/), just stating the following in the manual may not be enough.

> The easiest (and recommended) way to generate this nonce is to use your OS's random number generator (/dev/urandom on UNIX systems). Don't worry about accidental collisions, the nonce is big enough to make them virtually impossible.

Using `/dev/urandom` is [actually surprisingly difficult](https://insanecoding.blogspot.com/2014/05/a-good-idea-with-bad-usage-devurandom.html):

1. read(2) can get interrupted, violating the expectations some programmers may have, resulting in less random bytes than expected;
1. If you care about your randomness not being manipulated by an attacker that already basically owns the machine, verifying the device numbers between various operating systems is difficult because the operating systems are free to re-number them and there is a time of check/time of use disparity between the device number verification and the time; and
1. `/dev/urandom` may not necessarily be a CSPRNG on the OS the code is being run on.

The point is that doing random numbers is difficult, just like the cryptographic primitives provided in Monocypher are. Providing some way to wrap the RNGs of the most relevant operating systems (Windows, macOS, Linux, Solaris, FreeBSD, OpenBSD, NetBSD) or at least some further reading in the documentation may be a good idea.

**Comment by LoupVaillant** [comment]
Oh my, that's a whole can of worm you had me open with this blog. I think I will expand the manual and talk in more details about how one is supposed to get random numbers (I will probably disfavour `/dev/urandom` in favour of system calls like `getrandom(2)`). But I need to study this first —right now I'm in over my head.

Adding OS specific wrappers is out of scope. Monocypher has zero dependency, and I'd like to keep it that way.

About your specific points:

1. Shit, the same is true of `getrandom(2)`: can't request more than 256 bits at a time without risking interruption. But that's not so bad: Monocypher's private keys are 32 bytes, and the biggest nonces are 24 bytes. There is therefore hardly any reason to request more than 256 bits at a time, and the simplest, most obvious way of getting random data is actually the correct one.

2. If your machine is compromised, you are screwed, period. I don't worry about this scenario the same way a compiler pretends Undefined Behaviour doesn't exist, because I really don't know how to deal with that. If you think your machine may be compromised, stop using it this very second.

   _(The article you link to says the goal of chroot is to isolate the application from the rest of the system. Not so. It is meant to isolate the *system* from the application, so that compromising the application does not automatically compromise the system. If the system is already compromised, the application is hosed anyway.)_

3. I would just give up on such crappy systems. Can't do crypto without randomness. I just can't.

As a related note, I think this paragraph from the `urandom` Linux man page is bullshit:

> While  some  safety margin above that minimum is reasonable, as a guard against flaws in the CPRNG algorithm, no cryptographic primitive available today can hope to  promise  more  than  256 bits of security, so if any program reads more than 256 bits (32 bytes) from the kernel random pool per invocation, or per reasonable reseed  interval (not  less  than one minute), that should be taken as a sign that its cryptography is _not_ skillfully implemented.

Yes, ciphers today don't have more than 256 bits of security. No, it does not follow that we can't get more than 256 bits of pseudo-random data out of them without re-seeding. Stream ciphers *work* They can generate gigabytes of pseudo-random data with nothing more than 256 seed bits, and so can a kernel's PRNG. If Linux's PRNG can't, that's a bug. But if whoever wrote this paragraph didn't know what they were talking about, that doesn't bode well for the PRNG itself… Let's hope this paragraph is merely outdated.
