### ISSUE TITLE
How to credit your license(s)?

### ISSUE THREAD

**Issue by HACKERALERT** [LoupVaillant/Monocypher#214]
Sorry if this is not necessarily related to Monocypher. Being relatively inexperienced with licensing, how should I credit your work?

> This is Picocrypt's bindings to <a href="https://github.com/LoupVaillant/Monocypher">Monocypher</a>, the secure and audited library in which Picocrypt uses for ChaCha20. Monocypher's dual license (https://github.com/LoupVaillant/Monocypher/blob/master/LICENCE.md) applies.

Is something like this considered okay and ethical? Thanks. (This is a modified binding to the original Go bindings that I forked from demonshredder and fixed, so I'm not sure about the licensing since it's modified)

**Comment by LoupVaillant** [comment]
Hi,

Yes, that's perfectly okay. Legally speaking, you can basically do whatever you want. As for which licence applies, our licences allow you to redistribute Monocypher under the GPL (that was an intended use case). That may make your life simpler.

I only have one wish: please link to the https://monocypher.org web site instead of (or in addition to) the github repository. Just to make clear monocypher.org is the canonical resource.

**Comment by HACKERALERT** [comment]
Great, thank you!

> As for which licence applies, our licences allow you to redistribute Monocypher under the GPL (that was an intended use case).

So Picocrypt, the project which I mentioned above, is GPLv3 licensed, so that should be fine. Nice :)

As for your wish, no problem at all, I will link to https://monocypher.org for the homepage. I want to credit you properly for the excellent work you have done. Keep up the great work!
