### ISSUE TITLE
MSVC warnings in 3.1.2

### ISSUE THREAD

**Issue by mikejsavage** [LoupVaillant/Monocypher#215]
Probably junk but here you go:

```
monocypher.cpp(1685): warning C4319: '~': zero extending 'const u32' to 'u64' of greater size
monocypher.cpp(1738): warning C4319: '~': zero extending 'u32' to 'u64' of greater size
monocypher.cpp(2930): warning C4456: declaration of 'i' hides previous local declaration
monocypher.cpp(2929): note: see declaration of 'i'
monocypher.cpp(2934): warning C4456: declaration of 'i' hides previous local declaration
monocypher.cpp(2929): note: see declaration of 'i'
```

**Comment by LoupVaillant** [comment]
Hmm, I see you tested this against version 3.1.2.

The hidden declarations have been corrected on [commit 8c5bca](https://github.com/LoupVaillant/Monocypher/commit/8c5bcacdecafd23928a048728a10c5f414d40ea2). 

The other two warnings have yet to be fixed, good catch. I'm not sure how to go about it. See, MSVC is wrong here: the zero extension was intentional. if you write `~(u64)xr`, the tests fail. The best I can do is make the conversion explicit. That is, write `(u64)~L[i]` and  `(u64)~xr[i]` instead of just `~L[i]` and  `~xr[i]`. It's described on the patch below.

Is that patch enough to shut up MSVC? If it isn't, I'm willing to add a comment specifying that the zero-extension is intended. It won't suppress the warning, but at least it will explain to human reviewers.

```C
diff --git a/src/monocypher.c b/src/monocypher.c
index 46bfe68..84f543f 100644
--- a/src/monocypher.c
+++ b/src/monocypher.c
@@ -1609,7 +1609,7 @@ static int is_above_l(const u32 x[8])
     // (-L == ~L + 1)
     u64 carry = 1;
     FOR (i, 0, 8) {
-        carry += (u64)x[i] + ~L[i];
+        carry += (u64)x[i] + (u64)~L[i];
         carry >>= 32;
     }
     return carry;
@@ -1662,7 +1662,7 @@ static void mod_l(u8 reduced[32], const u32 x[16])
     // xr = x - xr
     u64 carry = 1;
     FOR (i, 0, 8) {
-        carry  += (u64)x[i] + ~xr[i];
+        carry  += (u64)x[i] + (u64)~xr[i];
         xr[i]   = (u32)carry;
         carry >>= 32;
     }
```

**Comment by LoupVaillant** [comment]
Nevermind, I reproduced the issue with the compiler explorer. Should be fixed now.

**Comment by mikejsavage** [comment]
Can confirm master fixes it and the explicit cast above doesn't

Thanks!
