### ISSUE TITLE
Rename primary branch to avoid problematic terms?

### ISSUE THREAD

**Issue by pandame** [LoupVaillant/Monocypher#219]
The term master is [known to be problematic](https://sfconservancy.org/news/2020/jun/23/gitbranchname/) ([see also](https://lore.kernel.org/git/CAOAHyQwyXC1Z3v7BZAC+Bq6JBaM7FvBenA-1fcqeDV==apdWDg@mail.gmail.com/)). Git upstream has [moved to rename the primary branch to `main`](https://lore.kernel.org/git/pull.656.v4.git.1593009996.gitgitgadget@gmail.com/).

In light of this, I'd like to ask that Monocypher rename the primary branch to `main`, too.

[GitHub provides a guide on how to do this renaming.](https://github.com/github/renaming)

**Comment by samuel-lucas6** [comment]
This reminds me of the case of Justin Trudeau saying 'peoplekind' despite the dictionary definition of 'mankind' being 'the whole human race, including both men and women'.

The dictionary definition of 'master' is not limited to 'one that has control over another person, a group of persons, or a thing', meaning it shouldn't be interpreted in that way in this context. Git and GitHub have nothing to do with that context, so if you're evaluating the term based on the dictionary definition, which is what people should be doing, then calling it the 'master branch' isn't offensive.

> On the other hand, I have yet to see even a single account of someone with documented enslaved ancestry being personally hurt, or even personally offended, by the use of the term. "Master" is also used in other contexts: master’s degree, chess masters and grandmasters, mastering a discipline, a dog’s master… and I’ve never seen any complaint about those.

I completely agree. I highly doubt anybody complained about the term 'master' in this context until recently when the BLM movement blew up. It seems far more likely that people are claiming the term is offensive by proxy when the vast majority of people aren't bothered whatsoever.

Lastly, it's ironic that 'git' means 'a person, especially a man, who is stupid or unpleasant'. There's a better case for renaming git than the master branch. When you define git that way, GitHub doesn't sound so good.

Therefore, I would argue that renaming the master branch is pointless at best and problematic for people relying on the master branch at worst.

**Comment by rgilton** [comment]
> On the other hand, I have yet to see even a single account of someone with documented enslaved ancestry being personally hurt, or even personally offended, by the use of the term.

Can you see that someone with such ancestry _might_ feel uncomfortable with the use of this term?

As a user of this library with it embedded in various test systems, I would have no issue with the branch being renamed to `main`.

**Comment by samuel-lucas6** [comment]
> Can you see that someone with such ancestry might feel uncomfortable with the use of this term?

No, because the dictionary definition of 'master' in this context is 'an original of something, such as a document, recording, or film, from which copies can be made'. As I explained in my reply, it has nothing to do with slavery, so why is it being discussed as if it's related to slavery? People are well aware that words often have multiple meanings that apply in different contexts, and it's quite clear that the master branch refers to the original branch. Assuming the master branch has any relation to slavery is a massive jump.

> As a user of this library with it embedded in various test systems, I would have no issue with the branch being renamed to main.

The main reason for not renaming the master branch, aside from potentially causing issues for people relying on it, is that the entire argument in favour of a rename is blatantly flawed. All this debate needs is a dose of common sense. Shall we burn all books that contain the word 'master' now? Perhaps we should rename Masters degrees? How far do we go? Why? To please a very small minority deliberately, in some cases, misinterpreting the definition of a word.

**Comment by LoupVaillant** [comment]
> Can you see that someone with such ancestry _might_ feel uncomfortable with the use of this term?

Before a group of determined people went out of their way to tell everyone how offensive "master" is, I’m not sure anyone was actually offended. Now that they _have_, I can. In any case, I’m uncomfortable being pressured to spend time and energy on such hypotheticals. Trying to provide tools that may help vulnerable people communicating safely is enough work already.

> As a user of this library with it embedded in various test systems, I would have no issue with the branch being renamed to `main`.

Noted, thanks.
