### ISSUE TITLE
Symbol name collisions with libsodium

### ISSUE THREAD

**Issue by snej** [LoupVaillant/Monocypher#224]
Both Monocypher and libsodium use `crypto_` as a prefix in their symbol names. As C has no notion of namespaces, this means there can be symbol collisions, both at compile time and at link time. It may seem unlikely for a program to use both libraries, but it could easily and silently occur if they are transitive dependencies. Or, as in my case, a program might directly use one library but also need to link 3rd party code that uses the other.

### Compile-time issues

If you include both of their headers in the same compilation unit, you get errors due to symbols that they both define, `crypto_sign` and `crypto_sign_update`:

```
// crypto_test.c
#include "monocypher.h"
#include <sodium.h>
```

Output (Clang 12):
```
In file included from crypto_test.c:12:
In file included from /opt/homebrew/include/sodium.h:41:
/opt/homebrew/include/sodium/crypto_sign.h:62:5: error: conflicting types for 'crypto_sign'
int crypto_sign(unsigned char *sm, unsigned long long *smlen_p,
    ^
In file included from crypto_test.c:11:
/Users/snej/Projects/bonsai/vendor/monocypher-cpp/vendor/monocypher/src/monocypher.h:218:6: note: previous declaration is here
void crypto_sign(uint8_t        signature [64],
     ^
In file included from crypto_test.c:12:
In file included from /opt/homebrew/include/sodium.h:41:
/opt/homebrew/include/sodium/crypto_sign.h:88:5: error: conflicting types for 'crypto_sign_update'
int crypto_sign_update(crypto_sign_state *state,
    ^
In file included from crypto_test.c:11:
/Users/snej/Projects/bonsai/vendor/monocypher-cpp/vendor/monocypher/src/monocypher.h:336:6: note: previous declaration is here
void crypto_sign_update(crypto_sign_ctx_abstract *ctx,
     ^
```

You could just say "don't include them both in the same source file." True, it's possible to avoid that with some indirection even if a function somehow needs to call both libraries (e.g. a function I'm trying to write that tests the interop of key-pairs generated by both libraries.)

### Link-time issues

But I'm more worried about link-time issues. I don't know if there are any functions that both libraries define with exactly the _same_ signatures; if there are any, the compiler won't complain about them ... but they obviously can't both exist in the same binary.

Most of the time the linker would complain about this, but because I'm compiling Monocypher from source but linking libsodium from a precompiled static library (.a file), the linker will give the locally-compiled symbol prededence and _silently discard the one from the library_ instead of reporting a duplicate-symbol error. (I don't know if this behavior is universal, but that's how the macOS linker works; I just tested it.) This would cause horrible effects at runtime if the two functions did different things.

### Workarounds

I'm assuming you don't want to rename all of Monocypher's symbols to use a different prefix, as this would break existing client code.

* Compile Monocypher as C++. This will 'mangle' the function names, making them different. Only applicable if the host program is written in C++. Requires editing `monocypher.h` to remove the `extern "C" { ... }` wrapper. Will likely require some changes to the Monocypher source code to let it compile as C++ -- the usual problem is implicit casts from `void*`.
* Write a list of preprocessor macros that rename every symbol, e.g. `#define crypto_sign monocypher_sign`, then arrange for those to be `#included` before the Monocypher header and source code. Works, without requiring source changes, but requires writing a bunch of tedious macros, which need to be updated if the Monocypher API changes. Won't work if Monocypher and libsodium are included in the same compilation unit. May confuse some IDE features.

**Comment by LoupVaillant** [comment]
I’ve thought about this issue since the very beginning. My stance basically is, "you only need one crypto library", especially since compatibility is only pursued opportunistically. Which is why I settled for the short "crypto_" prefix instead of something like "monocypher_".

> I'm assuming you don't want to rename all of Monocypher's symbols to use a different prefix

I don’t, but the user can: just use a sed command or the search & replace feature of an editor. Here’s an example of decompressing a tarball, then run sed on it to rename everything.

    $ tar -xzf monocypher.-3.1.2.tar.gz
    $ cd monocypher-3.1.2
    $ find . -name "*.*" | egrep ".(c|h)$" | xargs sed ’s/crypto_/foobar_/`

All the tests should work after the rename.

> Workarounds

* I could add a script to officially support this edit of the source code.
* I’ve never done it, but I heard the symbols in object files (.a, .so) can be renamed.

**Comment by fscoto** [comment]
> I’ve thought about this issue since the very beginning. My stance basically is, "you only need one crypto library", especially since compatibility is only pursued opportunistically. Which is why I settled for the short "crypto_" prefix instead of something like "monocypher_".

This assumption holds only if Monocypher provides everything necessary. Monocypher and libsodium do not fully overlap: For example, Monocypher provides both Elligator mappings, libsodium leaves you only with the with the forward map. libsodium provides Ristretto, Monocypher has no meaningful way to get at the internals to even build it yourself. libsodium had a padding algorithm, Monocypher doesn't (even though we said we would, oops). libsodium gets you hardware accelerated AES-256-GCM, Monocypher relies on ChaCha20-Poly1305 only. Depending on your exact needs, you might actually need two cryptography libraries.

Having said that, a rename of every function ever would break Monocypher compatibility to the point you might as well rename the project to something else and start fresh with a 0.x.

Ultimately, workarounds could be documented, but there's no proper solution for programs written in C that do not vendor Monocypher and instead rely on a port/package. Personally, I don't think this can be resolved in a reasonable manner.

What would be interesting, however, is *what features* drive this kind of double adoption. Maybe there would be room for a spin-off/automatically generated subset of functions if there happen to be common scenarios that Monocypher is desireable for but only in part. I realize this is considerably easier to say when I'm not on the hook to write and maintain the code, only the documentation.

**Comment by snej** [comment]
> the need for several libraries will lessen

But transitive dependencies are still a problem. Some developers will still choose to use libSodium. If my program uses libFoo and libBar, where libFoo uses Monocypher and libBar uses Sodium, then link-time collisions will still occur. And it may not be at all obvious to me what's going wrong, since I may not even be aware what crypto libraries libFoo and libBar use.

This can be avoided if libFoo and libBar are linked dynamically (and the `crypto_*` symbols are made private to each dylib.) Unfortunately there are major use cases where dynamic linking isn't possible, such as embedded systems.

I can't tell you what to do, but If I were in this situation, I'd bite the bullet and rename my API functions to use a different unique prefix, then for backward compatibility provide a header that contains a bunch of `#defines` to remap the old names to the new ones.

**Comment by LoupVaillant** [comment]
First, I will note that both OpenSSL and libsodium use the `crypto_` prefix. Both had the same idea about being the only cryptographic library you’ll ever need. This played a huge part in my initial decision to do the same.

_(Rant: also, cursed be the lack of namespace of any kind, I want proper modules: no stinking prefix inside the module, the module name provides a default prefix for users, and that prefix can be overridden at import time.)_

> But transitive dependencies are still a problem.

Ah. Didn’t see that one coming to be honest.

> If my program uses libFoo and libBar, where libFoo uses Monocypher and libBar uses Sodium

The first question that occurs to me then is, barring compatibility, why would you do that? If libFoo and libBar are using a cryptographic library, I expect they are one of the following:

- A library that implement one or more cryptographic constructions (no I/O, only buffers)
- A library that implements a file format (no I/O, only buffers).
- A library that implements a network protocol (no I/O, only buffers).
- A high-level library that does one of the above, *and* deals with I/O.

I have yet to write dedicated libraries for the above, so I’d understand why you’d use libNetwork that happens to use libsodium, and libFile that happens to use Monocypher. I should work on lessening that problem by writing those libraries (at least the I/O free ones). On the other hand, I’d have a harder time understanding why you’d need two different file formats, or two different network protocols, unless of course I forgot a use case.

> This can be avoided if libFoo and libBar are linked dynamically (and the `crypto_*` symbols are made private to each dylib.) 

I would be extremely surprised to learn something similar is not possible for static libraries as well.  Name clashes may make the build more complex (we must tell libFoo to only link with Moncypher, and tell libBar to only link with libsodium), but I don’t believe in an impossibility.

> Unfortunately there are major use cases where dynamic linking isn't possible, such as embedded systems.

One big contributor of Monocypher’s success is the fact that libsodium isn’t exactly embedded friendly. I do acknowledge other use cases though, such as hiding the structure of your program to end users.

> If I were in this situation, I'd bite the bullet and rename my API functions to use a different unique prefix, then for backward compatibility provide a header that contains a bunch of `#defines` to remap the old names to the new ones.

That would break most language bindings. Python bindings using ctypes for instance do not even use C headers. Instead they redefine everything on the Python side, effectively rewriting the header in Python syntax. The `#define` won’t be able to hide the rename, we’d have to `sed ’s/crypto_/foobar_/g’` the Python bindings as well. Given the stability I’m trying to achieve, I think this is a show stopper.

I believe providing an official script to let users do the mass rename themselves is much better. It won’t solve all problems, but at least it should satisfy people people who _wish_ they could rename everything, but don’t _dare_ because cryptographic code is scary.

**Comment by LoupVaillant** [comment]
Sorry about the unsatisfying fix, but I felt this was the best I could do.
