### ISSUE TITLE
Line count on the website mismatches observations

### ISSUE THREAD

**Issue by CuleX** [LoupVaillant/Monocypher#23]
The [website](http://loup-vaillant.fr/projects/monocypher/) says that "Monocypher takes less than 1300 lines of code". This is no longer true. By no measures I could get less than 1300.

Methods attempted:

* `wc -l monocypher.c` (1649)
* `grep -v '^$' monocypher.c|wc -l` (1492)
* [sloccount](https://www.dwheeler.com/sloccount/), which gets very close (1309)

You may want to either adjust the figure or note how you got your number.

(In more positive news, sloccount thinks monocypher.c costs $35,845 to develop.)

**Comment by LoupVaillant** [comment]
Oops, this number is outdated, probably from version 1.0.1 (with sloccount). I have since tweaked the loading code of Blake2b, Chacha20, and Poly1305, and lost a few more lines. I'll update it again when we release 1.0.2 (with your new documentation and my new test suite).

It was worth it, though. Chacha20 and Blake2b are now almost as fast as Libsodium (Chacha20 and Blake2b are about 10% slower, and Poly1305 is 7% *faster* than libsodium).

**Comment by LoupVaillant** [comment]
The web site have been corrected:

> Monocypher is a little over 1300 lines of code (counted with sloccount), small enough to allow comprehensive audits.
