### ISSUE TITLE
Packaging is not as easy as it should be

### ISSUE THREAD

**Issue by LoupVaillant** [LoupVaillant/Monocypher#24]
Packages started to appear, but we've learned since #19 that packagers make mistakes. This suggest the procedure to packages Monocypher lacks either automation or documentation —possibly both.

We should make the packager's life easy. I suggest the following:

* Add a system wide installation script (or Makefile) with sensible defaults for POSIX systems. Possibly provide both static and dynamic libraries.
* Add a `PACKAGING.md` file or similar to motivate these choices.
* Have a way to easily link to a Monocypher installation (might be an environment variable, might be `pkg_config`).

**Comment by CuleX** [comment]
> * Add a system wide installation script (or Makefile) with sensible defaults for POSIX systems.

An `install` Makefile target sounds like what people would expect. I'd highly suggest you respect the `DESTDIR` and `PREFIX` variables; packagers are likely to rely on it and are always glad to see it. [FreeBSD ports](https://www.freebsd.org/doc/en/books/porters-handbook/porting-prefix.html) are similarly expected to follow it, so assume it's a convention by now.

> Possibly provide both static and dynamic libraries.
>
> * Have a way to easily link to a Monocypher installation (might be an environment variable, might be `pkg_config`).

Compilation as a library is an entirely separate issue.

I'd suggest a `library` target that depends on the `static-library` and `dynamic-library` targets. The result should be a static library (`.a`) and a dynamic library (`.so`). POSIX mandates usage of [ar(1)](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/ar.html) AFAICT to create archives.

libtool exists, but I'm not sure how relevant it is if the baseline is "POSIX" and not "things that don't do POSIX at all or pretend to do POSIX but not really" (e.g. VMS, Windows). It's also a GNU monstrocity.

People will likely expect pkg-config(1) files. See [the pkg-config guide](https://people.freedesktop.org/~dbn/pkg-config-guide.html#writing). My environment is already a bit messy from all the variables things expect (`JAVA_HOME`, etc.) so that relying on pkg-config would be sane.

It's important that you stress that Monocypher *is* a drop-in solution like TweetNaCl is in the README: Adding it to the source distribution of your application is equally valid as linking to a library provided by the OS. Monocypher should stop being a moving target once it's gotten an external audit (Should a reminder issue be made about external audits? I wonder if the EFF would be interested in sponsoring an audit for a crypto library) so that dropping it in and forgetting to update it for all eternity should be unproblematic as long as the implemented cryptographic algorithms aren't compromised.

> Add a `PACKAGING.md` file or similar to motivate these choices.

I agree. The minimum content would be an explanation that `make install` behaves as expected (`DESTDIR`/`PREFIX`) and that running the selftest is highly recommended to verify compatibility with the platform. It should be encouraged, but not required, to compile the `self` executable but obviously not put it in `/usr/bin/`, so that users can verify their installation works.

You should also stress the licensing. Distributions usually also keep track of the involved licenses and this one probably falls under "custom".

People who package Monocypher may not be familiar to them. They might think that `make` should work, see it fails on the `sodium` target and assume that libsodium is a dependency after all. That should be avoided through documentation, ideally.

Also keep track of compatibility with alternative libc implementations (musl, uClibc). Systems like [Alpine Linux actually use them](https://alpinelinux.org/about/). It's usually a "try and see" thing with many projects but this should probably be promoted to a supported path.

Other notes:

* Remember to create release distributions in the form of tarballs. It seems Debian works by taking upstream tarballs and [adding their own `debian/` directory with meta information](https://www.debian.org/doc/manuals/maint-guide/dreq.en.html).
* At least Debian also writes and includes package changelogs. Having a changelog ready to copy and paste on each release would be useful.

**Comment by LoupVaillant** [comment]
Thanks for all those details, I would have missed most of them. :fearful:

> libtool exists, but I'm not sure how relevant it is if the baseline is "POSIX" and not "things that don't do POSIX at all or pretend to do POSIX but not really" (e.g. VMS, Windows).

I heavily suggest Windows users drop `monocypher.c` and `monocypher.h` into their projects (and compile them as C++ if they have any trouble compiling them as C). One-or-two files drop-in libraries are pretty popular on Windows, so I consider further support unnecessary.

> [Libtool is] also a GNU monstrocity.

I'd like to avoid it if possible. Since Monocypher has zero dependency (not even libc), we should be good.

> People who package Monocypher may not be familiar to them. They might think that make should work, see it fails on the `sodium` target and assume that libsodium is a dependency after all.

Yeah, I intend to solve that with #14. Future tarball releases will include a comprehensive self-consistency test suite, that depends on nothing but `malloc()` and `printf()` (possibly not even `malloc()`).

> Also keep track of compatibility with alternative libc implementations (musl, uClibc).

Hopefully, this won't be necessary. Surely their `printf()` implementation behaves the same as glibc?

> I wonder if the EFF would be interested in sponsoring an audit for a crypto library

Oh that would be soo nice! They probably have other priorities though. :disappointed:

**Comment by CuleX** [comment]
> I heavily suggest Windows users drop `monocypher.c` and `monocypher.h`

Yeah, as long as this kind of thing is documented in `PACKAGING.md`, that's good. This is one of the big things Monocypher has over libsodium.

> Surely their `printf()` implementation behaves the same as glibc?

glibc actually has a lot of extensions to `printf()` as specified in C. However, you're not doing anything fancy beyond number padding, which is supported [even on the most limited `printf()` implementation I've seen](http://www.sparetimelabs.com/printfrevisited/printfrevisited.php) (embedded devs working with really narrow constraints seem to replace `printf()` sometimes because it's usually huge to compared everything else). Therefore, you can assume `printf()` to be sane enough for your purposes.

> Oh that would be soo nice! They probably have other priorities though.

You won't know until you try asking.

**Comment by LoupVaillant** [comment]
Hi, I've just pushed a massive commit to help with the packaging and testing issues. What do you think?

**Comment by CuleX** [comment]
"Massive" hits the nail on the head indeed.

This seems mostly okay, but I did find some things. Where possible, I commented on the commit; for everything else, see this list:

# Build

`dist.sh` seems like it could benefit from [`set -e`](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#set); it's not impossible that it can fail. A very recent libsodium (as measured by what ships with Debian stable) is now a hard build dependency; you used to be able to just run the self tests separately. I feel like this is a bit of a regression.

# TODO List

>Stuff left to do:
>
>- Review and finalise the tests.

This probably needs no re-stating, but remember that the idea is that a user of Monocypher can call `crypto_selftest()` or such on startup if desired.

>[...]
>
>- Have the makefile install Monocypher

Did we ever solve the static library vs. dynamic library question?

>- Automate archive generation (and print the archive's blake2 hash).

As much as I understand you like BLAKE2 (and for good reason), please keep the following in mind:

1. `b2sum` was a very recent addition to GNU coreutils. It was added in [late 2016](https://git.savannah.gnu.org/cgit/coreutils.git/commit/?id=ea94589e9ef02624a3837f97f80efd7d3dcf56bf). As such, it is unavailable on anything prior to that. RHEL 7 doesn't have it yet, neither would any Ubuntu LTS release.
2. There is no BLAKE2 hashing utility on any other OS as far as I can see. Therefore, to verify the checksum, people would require Monocypher to be available already, leading to an indirecy dependency on itself.

For these reasons, I'd strongly suggest you stick to SHA-512 for the hash.

# The README

You may want to update `README.md` on how to work with this new tree. Since you apparently don't want people to get Monocypher from git anymore, strongly encourage the tarball distribution; add a direct link to a `Monocypher-latest.tar.gz` to the README.

*Right now, the documentation mismatches the state of the GitHub repository*. I'd like to suggest you either move this into a branch until it is finished or update the README as soon as possible.

**Comment by LoupVaillant** [comment]
Crap, I forgot the makefiles. Did I forget anything else?

**Comment by CuleX** [comment]
Since @secworks brought macOS up, I checked it out. Apparently, [libraries on the macOS platform end in *.dylib](https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/DynamicLibraryDesignGuidelines.html#//apple_ref/doc/uid/TP40002013-SW23).

However, I'm no expert on macOS. Do we care about brew? Worst case, we'd either try OS detection (mildly yuck) or some kind of user-provided variable for the library suffixes.

**Comment by secworks** [comment]
I had no problems building and using the libs on Mac. And if someone (me perhaps) wants to get into brew they'll fix any problems. So I'd say don't do any adaptations now.

**Comment by LoupVaillant** [comment]
Now the man pages are done. Phew.

**Comment by CuleX** [comment]
Is it intentional that `README.md` still says "TODO: make install"?

**Comment by LoupVaillant** [comment]
Err… nope. Fixing it now.

**Comment by LoupVaillant** [comment]
I just noticed that my `pkg-config` file only supports static linking (`--libs`). I'd like to add dynamic linking support as well, and web searches fail me. Users could still use `--variable=prefix` to then get to `lib/libmonocypher.so`, but I was wondering if there was a more direct route.

**Comment by CuleX** [comment]
https://github.com/libevent/libevent/blob/master/libevent.pc.in

I'm not seeing anything that would prevent dynamic linking? The `Libs` line you're currently using should yield the correct invocation for dynamic linking.

**Comment by LoupVaillant** [comment]
Oh, I didn't know… Never done dynamic linking actually.
