### ISSUE TITLE
Split monocypher.c into a few separate files?

### ISSUE THREAD

**Issue by secworks** [LoupVaillant/Monocypher#35]
Aloha!

The monocypher.c is 1600+ is one gigantic file with all but the sha512 functionality. How about splitting the file inta few separate files? One for poly1305, chacha etc.
It would make reading the code a bit easier. And possibly to maintain.

**Comment by CuleX** [comment]
First of all, thank you for the suggestion. You seem to have a considerably greater background than I do with embedded platforms and with infosec in general, so take the following words cum granu salis.

I'm not sure if that's in line with the spirit of the project. From the [website](http://loup-vaillant.fr/projects/monocypher/):

>  Here are its main selling points:
>
> [...]
>
> * **Easy to deploy.** Just put `monocypher.c` and `monocypher.h` in your project. They compile as C99, C11, or C++, and have *zero* dependency.

It seems like one of the project's goals seems to be very easy deployability in the sense of just dropping two files into the source tree and being done with it.

As for making reading the code easier, I'm not sure if there's that much benefit to splitting the functionality up into separate files, especially where they are interconnected (e.g. argon2 pulling in BLAKE2), hindering the ability to search for function definitions because file boundaries have to be crossed. Once #24 is solved and Monocypher had a few thorough security audits that resulted in no security issues being diagnosed, I wonder what maintainability issues there will even be.

Obviously, @LoupVaillant will have to make the call, these are just my two (uneducated) cents.

**Comment by LoupVaillant** [comment]
Thank you for your input, @secworks (Oh crap your repo list is impressive), you're welcome to more.

---

Split files is how Monocypher originally started, actually. Then I saw TweetNaCl's single source file, and figured I could do the same. This has one trivial advantages, and a not so trivial one:

- Putting it all in one file avoids a couple repetitions: helper macros, typedefs, and serialisation. We could put them in a common include file, but I want to avoid namespace pollution. Serialisation functions in particular would add spurious symbols if put in a common separate file —and I don't want to turn them into macros for readability reasons.

- Putting it all in one file simplifies the installation process: just copy&paste `monocypher.c` and `monocypher.h` into your project, and voilà, you have a crypto library. (#24 aims to facilitate more conventional usages).

That last one is a big deal. I don't want my users to think about trivia, they already have other things on their minds (such as deciphering the API, learning about crypto, or just making their stuff work). I won't give up on that.

The gigantic file has not been a problem in practice. The various primitives are still nicely segregated, and finding one is just a matter of searching for the relevant string, instead of opening the relevant file. The trick is to pretend each section is its own separate file. They _were_ their own separate files once.

My current opinion is that separating the files is not worth the trouble, even with the SQLite trick.

---

_(If you're wondering why SHA-512 has its own separate file, that's because it's an option, for Ed25519 compatibility —my EdDSA uses Blake2b instead. I wouldn't even have implemented it if I haven't needed it for the initial tests.)_

**Comment by secworks** [comment]
I don't see much difference in dropping two files or 6 or so. Or just point to one extra source dir when including the sources into my project. Also. Splitting the files makes it easier if somebody would want to just include a couple of the functions. Having a single top level include file makes the integration into a project.

Just my humble opinion. BTW, the code is imho well written and easy to read. I would do a few things differently (having separate files for the big functions for example). I'm looking at your monocypher core and also your poly1305 tutorial which is really, really good (http://loup-vaillant.fr/tutorials/poly1305-design).

I'm actually looking at it to do a good HW-implementation. The current idea is to implement a multiplier-accumulator module and then instantiate 1, 2, 4 , 5 or even more in order to parallelize the processing. This would allow updating the poly1305 state really fast. 

A bit of a digress here I guess.

**Comment by secworks** [comment]
BTW: If you have been so strict at not having any options, I would ditch SHA512 and just have blake2b.

**Comment by secworks** [comment]
A stupid question btw. What is the advantage of this?
typedef uint8_t  u8;
typedef uint32_t u32;
typedef int32_t  i32;
typedef int64_t  i64;
typedef uint64_t u64;

**Comment by LoupVaillant** [comment]
> I don't see much difference in dropping two files or 6 or so.

Neither do I, but this tiny inconvenience is to be multiplied by the number of users. Moreover, "header only" libraries, or "one source file" libraries seem to be pretty popular, especially on Windows where the slightest dependency tends to be unwieldy. (UNIX distros have it easy with their package managers and standard folders for libraries.)

> Splitting the files makes it easier if somebody would want to just include a couple of the functions.

Correct. I'm beginning to see why you'd rather split the files. On the other hand, the advantage of including fewer functions looks limited:

1. The whole compiled binary weights only 253kb on my machine (200kb if using the `.so`), even under maximum optimisations.
2. Don't linkers do some dead code elimination by not including unused symbols?
3. If you want one function, you probably want the others. If you want encryption, you want authentication, and either key exchange or password hashing —possibly both. (A counter argument to this point is hashing and signatures, that one may indeed want in isolation.)

> BTW, the code is imho well written and easy to read.

Thanks!

> I'm actually looking at [your poly1305 tutorial] to do a good HW-implementation.

Sounds terrific! I also love that you're building on my work, I didn't expect this tutorial to have such concrete effects. By the way, looks like I should add a section about parallelising Poly1305, it's simpler than I expected.

> What is the advantage of [the typedefs]?

I like `u32` better than `uint32_t` because it's shorter. Since they're used all over the place, I believe they enhance readability a little bit. The same goes for my `FOR` macro (which by the way not everyone likes): shorter, less noise, thus more readable.

**Comment by CuleX** [comment]
> Neither do I, but this tiny inconvenience is to be multiplied by the number of users. Moreover, "header only" libraries, or "one source file" libraries seem to be pretty popular

https://github.com/nothings/single_file_libs

That's 3,054 stars right there. Regardless of right or wrong, that's a number. It happens to be a fairly big one.

**Comment by LoupVaillant** [comment]
Hmm, Monocypher is not listed. We'll need to work on that. :-)

**Comment by secworks** [comment]
Mos def.

**Comment by CuleX** [comment]
@LoupVaillant I was going to file that when the issue count hits 0 and 1.0.2/1.1.0 is out.

**Comment by LoupVaillant** [comment]
Yeah, good idea. It will be next to TweetNaCl, I'd like to be able to say _High Quality™_ too.

**Comment by CuleX** [comment]
Closed issues, 10/10 IRC replacament.
