### ISSUE TITLE
Should we alias multi-purpose functions?

### ISSUE THREAD

**Issue by LoupVaillant** [LoupVaillant/Monocypher#80]
This has become glaringly apparent when shuffling the header for ease of use by end users: some functions are either "missing" or have the wrong name.

`crypto_lock_init()` and `crypto_lock_auth()`, and `crypto_lock_ctx` do not have any `unlock` counterpart (they are used for both locking and unlocking). Also, `crypto_lock_auth()` is a general authentication function, that can authenticate additional data *and* the rest. A users writing (or reviewing) code using those functions might think the following:

    crypto_lock_ctx ctx;                            // wrong type! use crypto_unlock_ctx;
    crypto_lock_init(ctx, key, nonce);              // wrong init!
    crypto_lock_auth(ctx, aead, aead_size);         // not AEAD specific, still not unlocking!
    crypto_unlock_update(ctx, msg, msg_size);       // OK
    if (crypto_unlock_final(ctx, mac)) { abort(); } // OK

Should we add the following aliases?

    typedef crypto_unlock_ctx     crypto_lock_ctx
    #define crypto_unlock_init    crypto_lock_init
    #define crypto_lock_aead      crypto_lock_auth
    #define crypto_unlock_aead    crypto_lock_auth

We have `crypto_x25519()`, `crypto_key_exchange()`, and `crypto_x25519_public_key()`. End users are meant to use the last two, which then display inconsistent naming. Should we add the following alias?

    #define crypto_key_exchange_public_key  crypto_x25519_public_key

`crypto_sign_update()` is used for the first pass *and* second pass. Should we add the following aliases?

    #define crypto_sign_update_first_pass   crypto_sign_update
    #define crypto_sign_update_second_pass  crypto_sign_update

I'm a bit torn. On the one hand, I want to keep the minimum required to use Monocypher. On the other hand, I'd like to avoid needless confusion. I believe we should add some aliases, but not all:

* I would alias the `crypto_lock*()` functions, but not the context.
* I would alias `crypto_x225519_public_key()` to avoid the blatant inconsistency, *or* rename `crypto_key_exchange()` into `crypto_x25519_HChacha20()` (and keep the old name for backward compatibility). I'm not sure which is best.
* I would probably not alias crypto_sign_update.

@CuleX, @mikejsavage, what do you think?

**Comment by mikejsavage** [comment]
I noticed this while I was going over the examples

I agree it would be nicer to have symmetry between unlock/lock. It kind of looks like a typo/bug when you have lock and unlock calls interleaved while decrypting. Don't care about aliasing the context

Also agree on adding `crypto_key_exchange_public_key`. `crypto-x25519_HChacha20` seems awful :d

Also also agree on not aliasing crypto_sign_update, I don't think that's so bad

**Comment by CuleX** [comment]
Disclaimer: I write Ruby. Convenience aliases are our lifeblood. If you can foresee a programmer do something and it'll break, try to fix it with the most intuitive solution *if* it isn't dangerous to do so. We would do well to document the aliases, however.

# crypto_lock

I agreeing on all aliases for `crypto_lock` family.

I'm in favor of the context typedef, though. Monocypher *may* eventually get a new version that has a different unlock struct. Conditioning users into using an unlock struct may actually be beneficial. Some issues with the naming (e.g. `crypto_lock_auth`) mainly comes from using `lock` as both a transitive verb and as a way to refer to the used AE(AD) construction in general.

Maybe renaming the entire thing is in order; we *did* break API and ABI with `crypto_verify{16,32,64}` and the change in `crypto_argon2i` anyway.

# crypto_key_exchange

No objections on the proposed alias.

Against `crypto_x25519_HChacha20` because we're trying to keep the primitives out of the names for end user functions wherever possible.

# crypto_sign

Let's not. This one needs a lot of conscious effort to get right in the first place. The cognitive burden and manual reading being required here is a good thing.

**Comment by LoupVaillant** [comment]
> we're trying to keep the primitives out of the names for end user functions wherever possible.

Originally, I was not. Else the `crypto_blake2b*()` functions would have been called `crypto_hash()` instead. I thought I should expose the names of the primitives in the API to make sure users are aware of what they are using. Generic names ended up being used because concision was important.

Anyway, glad we agree on almost everything. I'll alias the whole `crypto_lock` thing, including the context, and add `crypto_key_exchange_public_key`. I'll try to update the documentation accordingly.

**Comment by LoupVaillant** [comment]
Corrected the issue [at the source code end](https://github.com/LoupVaillant/Monocypher/commit/a53da7eecd02e01e6b2eb3d0d1112de4184abd1f). Now we should update the docs. I believe noting the presence of aliases, as well as updating the examples, should be enough. Note that the aliases are `#define` macros, not proper symbols (or type, in the case of `crypto_unlock_ctx`). The documentation should reflect that.

I tried to use function pointers and `typedef` instead, but this ended up causing various compilation problems. `#define` is unsatisfying, but it looks like it's the best I can do.

**Comment by LoupVaillant** [comment]
Hi, I took the liberty to document the aliases myself (sorry @mikejsavage, I was running out of stuff to do before the next release). More a hassle than I anticipated, though.

Note that I more or less decided to document the aliases as if they were real functions. The fact they're aliases is documented in the relevant _implementation details_ sections.

So, can we close this?
