### ISSUE TITLE
Add RFC 7539 test vectors

### ISSUE THREAD

**Issue by secworks** [LoupVaillant/Monocypher#81]
RFC 7539 "ChaCha20 and Poly1305 for IETF Protocols" contains serveral test vectors for both ChaCha20, Poly1305 as separate constructs, as well for the combined construct. At least the test vectors for ChaCha and Poly1305 could be useful to add to Monocypher. This would show that the implementations in Monocypher seems to match other specs and implementations.

See for example chapter 2.5.2 for Poly1305 test vectors with a three block message with results for each block and final result.

https://tools.ietf.org/html/rfc7539

**Comment by LoupVaillant** [comment]
They are already included [here](https://github.com/LoupVaillant/Monocypher/tree/master/tests/vectors) and [there]() already. They are inserted alongside the random test vectors generated with libsodium.

Note that official test vectors are especially important for Poly1305, because some of them specifically tests some overflow that would be hard to detect with random tests.

**Comment by secworks** [comment]
I'm sorry, but I must have gone blind.

I'm searching for Poly1305 key bytes taken from RFC 7539 in the test vector file:
https://github.com/LoupVaillant/Monocypher/blob/master/tests/vectors/poly1305

As far as I can see, neither the test vectors from chapter 2.5 nor the one in A.5 are included. But the test vectors from A.3 are included. Should we try to add the others for completeness?

**Comment by LoupVaillant** [comment]
Oh, I've read your report too quickly, sorry. Time to pay *real close* attention.

I think the main reason for these omissions is, I merely included the test vectors from the appendix, and ignored the main text. I may even have thought the example in 2.5 was repeated in the appendix. It is also clearly meant as an implementation guide, not as a final verification tool. That said I don't see why I wouldn't include it. There, done.

Section A.5 however is different: it tests the whole AEAD construction, and that involves padding. Including it in a test vector would be both tedious and slightly different from the actual, official test vectors. Not worth it, considering libsodium generates most of my test vectors.

The real value of the test vectors from the RFC comes from test cases 5 to 11, which test various edge cases that are hard to come by by mere chance:

* If one uses 130-bit partial reduction, does the code handle the case where partially reduced final result is not fully reduced?
* What happens if addition of s overflows modulo 2^128?
* What happens if data limb is all ones and there is carry from lower limb?
* What happens if final result from polynomial part is exactly 2^130-5?
* What happens if final result from polynomial part is exactly 2^130-6?
* What happens if 5*H+L-type reduction produces 131-bit intermediate result?
* What happens if 5*H+L-type reduction produces 131-bit final result?

If not for those, I wouldn't be confident in the correctness of my implementation. Perhaps I'd have even gone full formal proof.

**Comment by secworks** [comment]
Thanks. Yes I totally agree on the usefulness of the test cases (that is why I looked at them). Thanks for adding the one from 2.5. I've also considered writing simple examples of using Monocypher to get the results from RFC 7539.

**Comment by LoupVaillant** [comment]
> I've also considered writing simple examples of using Monocypher to get the results from RFC 7539.

That's possible, but a bit tricky as well: there's the padding, and and the 96-bit nonce, which requires a dirty trick with `chacha20_set_ctr()` (basically, you put the least significant bits of the nonce in the most significant bits of the counter).

**Comment by secworks** [comment]
I was more specifically thinking of the test vectors for Poly1305. They don't have a nonce and should be straight forward. Esp the one in chapter 2.5.

**Comment by LoupVaillant** [comment]
Ah, OK.
