### ISSUE TITLE
Finish releasing 1.1.0

### ISSUE THREAD

**Issue by mikejsavage** [LoupVaillant/Monocypher#88]
website is down atm so i can't check it, but IIRC the wget/tar listing on the front page refers to 1.0.1 still, and there's no 1.1.0 on github

**Comment by LoupVaillant** [comment]
> website is down atm

Oops, I botched the TLS configuration, and the server no longer served the certificate. My bad.

> IIRC the wget/tar listing on the front page refers to 1.0.1 still,

Indeed, I should have updated this example. Should be good now. The download section was up to date.

>  and there's no 1.1.0 on github

I forgot to push the tag, sorry. Oh, and I'll try to upload the tarball as well. Last time I did it, GitHub told me "something went wrong" with the tarball (turned out noScript was blocking stuff without telling me clearly).

Should be all good now.
