### ISSUE TITLE
CC0 is not recommenden, Public Domain is not available everywhere.

### ISSUE THREAD

**Issue by aggsol** [LoupVaillant/Monocypher#94]
[CC itself recommends *not* to use CC0 for software.](https://wiki.creativecommons.org/wiki/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F). Please reconsider. This is similar like Public Domain *not* being available in many juristictions (Europe). MIT/BSD or GPL/[EUPL](https://joinup.ec.europa.eu/page/eupl-text-11-12) are better choices depending on your needs.

**Comment by mikejsavage** [comment]
It is dual licensed BSD/public domain, you can use BSD if you like!

**Comment by LoupVaillant** [comment]
First, am fully aware that not all jurisdictions let me put my work in the public domain. This is why I kept the [BSD fallback](https://github.com/LoupVaillant/Monocypher/blob/master/LICENCE.md).

Second, I think you have misread the following sentence from Creative Commons:

> Yes, CC0 is suitable for dedicating your copyright and related rights in computer software to the public domain, to the fullest extent possible under law. Unlike CC licenses, which should not be used for software, CC0 is compatible with many software licenses, including the GPL.

It's the other CC licences that should not be used for software. CC-0 is different. Granted, it wasn't OSI approved. But it wasn't rejected either. The OSI committee was unable to reach consensus because they were afraid of the patent clause in the CC-0. Creative Commons since withdrew their application.

I think we're okay, closing this.
